"""add directory entries

Revision ID: 1e64812a63db
Revises: b6eecab15539
Create Date: 2026-08-13 11:24:10.494329
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e64812a63db'
down_revision: Union[str, None] = 'b6eecab15539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('size_band', sa.String(length=50), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('device_count_is_floor', sa.Boolean(), nullable=False),
    sa.Column('highest_risk_class', sa.String(length=30), nullable=True),
    sa.Column('device_keywords', sa.Text(), nullable=True),
    sa.Column('example_devices', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('detail_url', sa.String(length=600), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('eudamed','mhra','manual')", name='ck_directory_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_ref', name='uq_directory_source_ref')
    )
    with op.batch_alter_table('directory_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_entries_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_entries_size_band'), ['size_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_directory_tenant_country', ['tenant_id', 'country'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_directory_tenant_country')
        batch_op.drop_index(batch_op.f('ix_directory_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_directory_entries_size_band'))
        batch_op.drop_index(batch_op.f('ix_directory_entries_country'))
        batch_op.drop_index(batch_op.f('ix_directory_entries_company_id'))

    op.drop_table('directory_entries')
    # ### end Alembic commands ###
