"""initial schema

Revision ID: c3238318c11f
Revises: 
Create Date: 2026-08-10 21:57:00.111745
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3238318c11f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('progression', sa.Float(), nullable=False),
    sa.Column('signal_quality', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'owner', 'period_type', 'period_start', name='uq_buddy_snapshot_period')
    )
    with op.batch_alter_table('buddy_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buddy_snapshots_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_buddy_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('size_band', sa.String(length=50), nullable=True),
    sa.Column('product_fit', sa.String(length=10), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('score_computed_at', sa.DateTime(), nullable=True),
    sa.Column('first_signal_date', sa.Date(), nullable=True),
    sa.Column('last_signal_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('watchlist','active','engaged','won','lost','dormant')", name='ck_companies_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_companies_tenant_name', ['tenant_id', 'name'], unique=False)
        batch_op.create_index('ix_companies_tenant_score', ['tenant_id', 'current_score'], unique=False)

    op.create_table('manager_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_segment', sa.String(length=200), nullable=True),
    sa.Column('parsed_geography', sa.String(length=200), nullable=True),
    sa.Column('parsed_signal_type', sa.String(length=80), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('weight_adjustment', sa.Float(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('surfaced_count', sa.Integer(), nullable=False),
    sa.Column('converted_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manager_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manager_insights_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('signal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('product_fit', sa.String(length=10), nullable=False),
    sa.Column('base_weight', sa.Float(), nullable=False),
    sa.Column('sources', sa.String(length=20), nullable=False),
    sa.Column('decays', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("product_fit IN ('A','B','both')", name='ck_signal_types_product_fit'),
    sa.CheckConstraint("sources IN ('manual','auto','both')", name='ck_signal_types_sources'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_signal_types_tenant_key')
    )
    with op.batch_alter_table('signal_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_types_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_contacts_tenant_company', ['tenant_id', 'company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('compounding_applied', sa.Boolean(), nullable=False),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'snapshot_date', name='uq_score_snapshot_company_date')
    )
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_snapshots_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type_key', sa.String(length=80), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('product_fit', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome_tag', sa.String(length=60), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('auto','manual','manager_insight','inbound','event')", name='ck_signals_source'),
    sa.CheckConstraint("status IN ('scored','review','unscored','rejected')", name='ck_signals_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_signals_confidence'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_company_detected', ['company_id', 'detected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_type_key'), ['type_key'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('outcome', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signal_id_at_time_of_contact', sa.Integer(), nullable=True),
    sa.Column('company_tier_at_time_of_contact', sa.String(length=10), nullable=True),
    sa.Column('company_score_at_time_of_contact', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('out','in')", name='ck_activity_direction'),
    sa.CheckConstraint("type IN ('email','call','linkedin','meeting','reply','note')", name='ck_activity_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id_at_time_of_contact'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_date'), ['date'], unique=False)
        batch_op.create_index('ix_activity_tenant_date', ['tenant_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_tenant_id'))
        batch_op.drop_index('ix_activity_tenant_date')
        batch_op.drop_index(batch_op.f('ix_activity_date'))
        batch_op.drop_index(batch_op.f('ix_activity_contact_id'))
        batch_op.drop_index(batch_op.f('ix_activity_company_id'))

    op.drop_table('activity')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_type_key'))
        batch_op.drop_index(batch_op.f('ix_signals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_company_id'))
        batch_op.drop_index('ix_signals_company_detected')

    op.drop_table('signals')
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_score_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_score_snapshots_company_id'))

    op.drop_table('score_snapshots')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_tenant_id'))
        batch_op.drop_index('ix_contacts_tenant_company')
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('signal_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_types_tenant_id'))

    op.drop_table('signal_types')
    with op.batch_alter_table('manager_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manager_insights_tenant_id'))

    op.drop_table('manager_insights')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_tenant_score')
        batch_op.drop_index('ix_companies_tenant_name')
        batch_op.drop_index(batch_op.f('ix_companies_tenant_id'))

    op.drop_table('companies')
    with op.batch_alter_table('buddy_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buddy_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buddy_snapshots_period_start'))

    op.drop_table('buddy_snapshots')
    # ### end Alembic commands ###
